name: Build LaTeX document
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Set global and remove compiled pdf
      run: |
        git config --global user.name ffyr2w
        git config --global user.email ffyr2w@users.noreply.github.com
        git pull
    
    - run: file emClarity-tutorial.pdf | grep -q ' PDF '
    - name: remove pdf if it is there
      if: success()
      run: |
        echo "emClarity-tutorial.pdf is there. Deleting it..."
        git rm emClarity-tutorial.pdf

    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: emClarity-tutorial.tex

    - name: Upload pdf to the master branch
      run: |
        git add emClarity-tutorial.pdf
        git commit -m "Automated upload"
        git push origin master
        
#     - name: Upload artifact
#       uses: actions/upload-artifact@gh-pages
#       with:
#         name: emClarity-tutorial-pdf
#         path: ./
#       if: always()
