name: Build LaTeX document
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Github Action for LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    - name: Upload pdf to the gh-pages branch
        run: |
          git config --global user.name ffyr2w
          git config --global user.email ffyr2w@users.noreply.github.com
          git checkout gh-pages
          git add main.pdf
          git commit -m "Automated upload"
          git push origin gh-pages
      
